# Generated by Django 5.0.1 on 2024-03-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0006_orders_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
