# Generated by Django 5.0.1 on 2024-10-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0008_alter_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
